### ISSUE TITLE
你好。我下载了项目但是缺少文件MineView.swift

### ISSUE THREAD

**Issue by zhao1zhihui** [Until-You-Possible/NetEaseMusic#7]

**Comment by zhao1zhihui** [comment]
依赖项也不全，麻烦有用修改下谢谢

**Comment by Until-You-Possible** [comment]
> 依赖项也不全，麻烦有用修改下谢谢

sorry，今天回去看下。我记得全部提交了的

**Comment by Until-You-Possible** [comment]
@zhao1zhihui 我查看了下本地的代码，首先你说的那个文件确实没有。相关的依赖如图
![issue@2x](https://github.com/Until-You-Possible/NetEaseMusic/assets/85671592/81d0306f-9440-4620-995c-e55892815b16)
![d@2x](https://github.com/Until-You-Possible/NetEaseMusic/assets/85671592/eada2f1d-d93e-44c2-84c7-773655f37e40)

**Comment by zhao1zhihui** [comment]
你好，我的依赖库下载不全是自身网络原因吗？这个依赖库是carthage

**Comment by zhao1zhihui** [comment]
我在工程中没有找到carthage的配置文件
